node_aes_names_DiagrammR <- function(all = F){
  c(#write conversion
    "shape",
    "style",
    "penwidth",
    "color",
    "fillcolor",
    "image",
    "fontname",
    "fontsize",
    "fontcolor",
    "peripheries",
    "height",
    "width",
    "x",
    "y",
    "group",
    "tooltip",
    "xlabel",
    "URL",
    "sides",
    "orientation",
    "skew",
    "distortion",
    "gradientangle",
    "fixedsize",
    "labelloc",
    "margin"
  )
}
edge_aes_names_DiagrammR <- function(all = F){
  c(#write conversion
    "style",
    "penwidth",
    "color",
    "arrowsize",
    "arrowhead",
    "arrowtail",
    "fontname",
    "fontsize",
    "fontcolor",
    "len",
    "tooltip",
    "URL",
    "label",
    "labelfontname",
    "labelfontsize",
    "labelfontcolor",
    "labeltooltip",
    "labelURL",
    "edgetooltip",
    "edgeURL",
    "dir",
    "headtooltip",
    "headURL",
    "headclip",
    "headlabel",
    "headport",
    "tailtooltip",
    "tailURL",
    "tailclip",
    "taillabel",
    "tailport",
    "decorate"
  )
}
node_aes_names_visNetwork <- function(all = F){
  #?visNetwork::visNodes()
  OUT <- c(
    "id",
    "label",
    "shape",
    "group",
    "level",
    # The types with the label inside of it are:
    # ... ellipse, circle, database, box, text
    # The ones with the label outside of it are:
    # ... image, circularImage, diamond, dot, star, triangle, triangleDown, hexagon, square and icon
    "size",
    "title",
    "value",
    "physics"
  )
  if(all){
    OUT <- OUT %>% append(
      c(
        "font",
        "color",
        "opacity",
        "fixed",
        "mass",
        "x",
        "y",
        "hidden",
        "image",
        "borderWidth",
        "borderWidthSelected",
        "brokenImage",
        "labelHighlightBold",
        "icon",
        "shadow",
        "scaling",
        "shapeProperties",
        "heightConstraint",
        "widthConstraint",
        "margin",
        "chosen",
        "imagePadding",
        "ctxRenderer"
      )
    )
  }
  return(OUT)
}
edge_aes_names_visNetwork <- function(all = F){
  #?visNetwork::visEdges()
  OUT <- c(
    "id",
    "from",
    "arrows",
    "to",
    "label",
    "title",
    "dashes",
    "physics"
  )
  if(all){
    OUT <- OUT %>% append(
      c(
        "color",
        "font",
        "value",
        "length",
        "width",
        "hidden",
        "hoverWidth",
        "selectionWidth",
        "selfReferenceSize",
        "selfReference",
        "labelHighlightBold",
        "arrowStrikethrough",
        "smooth",
        "shadow",
        "scaling",
        "widthConstraint",
        "chosen",
        "endPointOffset"
      )
    )
  }
  return(OUT)
}
